### ISSUE TITLE
后处理问题

### ISSUE THREAD

**Issue by yanjw1226** [long123524/SEANet_torch#1]
有两个问题想请教一下
1、预测的第二个输出是[6,1,256,256] 怎么获取边缘的输出
2、预测的mask还是存在地块的粘连，怎么通过后处理获取最终的地块矢量呢 谢谢

**Comment by yanjw1226** [comment]
![1689315364666](https://github.com/long123524/SEANet_torch/assets/33916793/277ea91c-cde5-46a7-9b37-eb34927db891)
![1689315383577](https://github.com/long123524/SEANet_torch/assets/33916793/eaa9753b-4156-427d-84be-1e31c56c3bd1)

就是这样的情况，是我数据预处理不对吗

**Comment by long123524** [comment]
你的结果很奇怪，首先确保标签质量和影像。数据集中需要三个标签，提供mask标签应是比较单一的地块。2.边缘输出你只输出融合的那一个就行，也就是最后一个会比较好。3.后处理你可以先去掉一些破碎的明显错误的图斑，亦或是利用边界输出优化mask。3.你可以从mask中得到二值边界（或者使用得到的边界预测结果），并转成矢量，利用道格拉斯普克等算法进行规则化，获得更优的矢量边界。

**Comment by yanjw1226** [comment]
感谢 原来最后一个就是融合的边界，
对 的确在等待您回复的时候，发现了标签问题重新处理了，由于标注是直接在大耕地地块的基础上进行分割小底裤操作，导致栅格化之后相邻地块是粘连的。所以我先把面转线，线转栅格后膨胀了3个像素让地块mask减去了contour，的确结果比以前的缝隙大了一下。目前mask的精度还是挺高的，还没做数据增强，迭代不到20次，F1 score快90，还是会存在一点粘连，数据质量不知道还有没有问题，我目前是采样成0.5m分辨率。
这个是训练的
![1689327241700](https://github.com/long123524/SEANet_torch/assets/33916793/78b121de-c53a-49b8-accd-f5c56feec956)
![1689327264382](https://github.com/long123524/SEANet_torch/assets/33916793/895e23ea-e080-4f93-87c8-0aac08c81e9f)

这个是预测的
![1689327227324](https://github.com/long123524/SEANet_torch/assets/33916793/bd149ef8-38ce-4f2d-98dc-ba6f9ac427a2)

**Comment by long123524** [comment]
mask看上去没啥问题，你的边界看起来都是合起来的，单个耕地应该是存在一定间隙的，标注是不是没有标注好。建议做数据增强，并迭代多一点

**Comment by yanjw1226** [comment]
好 谢谢 我再改一下试试
