### ISSUE TITLE
提取边界

### ISSUE THREAD

**Issue by Muziyi687** [long123524/SEANet_torch#10]
您好！我想将mask的数据换成contour的数据，以实现边界的提取，但是我现在预测输出的结果是错误的（如何用原mask，是可以提取出地块的），请问这个模型能否实现边界提取的操作呢？谢谢您！！！

**Comment by long123524** [comment]
> 您好！我想将mask的数据换成contour的数据，以实现边界的提取，但是我现在预测输出的结果是错误的（如何用原mask，是可以提取出地块的），请问这个模型能否实现边界提取的操作呢？谢谢您！！！

模型本身是可以提取mask、boundary和distance map的，输出的多任务结果。
