### ISSUE TITLE
获取地块边界

### ISSUE THREAD

**Issue by Muziyi687** [long123524/SEANet_torch#11]
您好，有个问题一直困惑我，我看到您论文的结果是有地块边界的，但是我试验了把mask的图像换成边界（把mask换成contour），并没法预测。我也试过直接用边界线当mask，但是这样的mask无法计算dist_contour和contour，也无法进行训练。如果我用面去预测，就只能得到一整块地块的边界，所以我想请问您，如何能得到一小块一小块地块的边界？谢谢您！

**Comment by long123524** [comment]
> 您好，有个问题一直困惑我，我看到您论文的结果是有地块边界的，但是我试验了把mask的图像换成边界（把mask换成contour），并没法预测。我也试过直接用边界线当mask，但是这样的mask无法计算dist_contour和contour，也无法进行训练。如果我用面去预测，就只能得到一整块地块的边界，所以我想请问您，如何能得到一小块一小块地块的边界？谢谢您！

模型本身的结构是同时预测mask，contour和distance，其中mask是地块（面）提取，contour是线提取，distance是距离图回归。你说的一小块地块的边界具体是什么呢？模型本身是可以预测出小patch的结果，例如256x266或者其他。

**Comment by Muziyi687** [comment]
> > 您好，有个问题一直困惑我，我看到您论文的结果是有地块边界的，但是我试验了把mask的图像换成边界（把mask换成contour），并没法预测。我也试过直接用边界线当mask，但是这样的mask无法计算dist_contour和contour，也无法进行训练。如果我用面去预测，就只能得到一整块地块的边界，所以我想请问您，如何能得到一小块一小块地块的边界？谢谢您！
> 
> 模型本身的结构是同时预测mask，contour和distance，其中mask是地块（面）提取，contour是线提取，distance是距离图回归。你说的一小块地块的边界具体是什么呢？模型本身是可以预测出小patch的结果，例如256x266或者其他。

小块地块是指一小块农田一小块农田，主要是边界，我看了您的代码（accuracy_evaluation.py），预测结果只是有mask对应的（面提取），无法得到contour（线提取），导致我不知道如何得到线（地块边界），麻烦您再给我解释一下具体如何提取出线。谢谢您！！

**Comment by Muziyi687** [comment]
> accuracy_evaluation.py

输出outputs2就行吗？

**Comment by Muziyi687** [comment]
> > > > 您好，有个问题一直困惑我，我看到您论文的结果是有地块边界的，但是我试验了把mask的图像换成边界（把mask换成contour），并没法预测。我也试过直接用边界线当mask，但是这样的mask无法计算dist_contour和contour，也无法进行训练。如果我用面去预测，就只能得到一整块地块的边界，所以我想请问您，如何能得到一小块一小块地块的边界？谢谢您！
> > > 
> > > 
> > > 模型本身的结构是同时预测mask，contour和distance，其中mask是地块（面）提取，contour是线提取，distance是距离图回归。你说的一小块地块的边界具体是什么呢？模型本身是可以预测出小patch的结果，例如256x266或者其他。
> > 
> > 
> > 小块地块是指一小块农田一小块农田，主要是边界，我看了您的代码（accuracy_evaluation.py），预测结果只是有mask对应的（面提取），无法得到contour（线提取），导致我不知道如何得到线（地块边界），麻烦您再给我解释一下具体如何提取出线。谢谢您！！
> 
> 你输出边界结果就可以了，模型有三个输出，你可以调整代码输出第二个结果就是边界，二值化后就是地块边界图，

输出outputs2就行吗？

**Comment by Muziyi687** [comment]
我改成output2了，会报错
  0%|                                                                                                                           | 0/216 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "e:\DP\SEANet_torch\accuracy_evaluation.py", line 135, in <module>
    predict_2 = torch.flip(outputs5, [-1])
TypeError: flip(): argument 'input' (position 1) must be Tensor, not list

**Comment by long123524** [comment]
> 我改成output2了，会报错 0%| | 0/216 [00:00<?, ?it/s] Traceback (most recent call last): File "e:\DP\SEANet_torch\accuracy_evaluation.py", line 135, in predict_2 = torch.flip(outputs5, [-1]) TypeError: flip(): argument 'input' (position 1) must be Tensor, not list

output2内含多层级边界输出，所以是列表。你输出最后一个边界就好，outputs2[-1]

**Comment by Muziyi687** [comment]
> > 我改成output2了，会报错 0%| | 0/216 [00:00<?, ?it/s] Traceback (most recent call last): File "e:\DP\SEANet_torch\accuracy_evaluation.py", line 135, in predict_2 = torch.flip(outputs5, [-1]) TypeError: flip(): argument 'input' (position 1) must be Tensor, not list
> 
> output2内含多层级边界输出，所以是列表。你输出最后一个边界就好，outputs2[-1]

for i, (img_file_name, inputs, targets1, targets2, targets3) in enumerate(
            tqdm(valLoader)
    ):
        inputs = inputs.to(device)
        targets1 = targets1.to(device)

        outputs1, outputs2, outputs3 = model(inputs)
        outputs4, outputs5, outputs6 = model(torch.flip(inputs, [-1]))
        predict_2 = torch.flip(outputs4, [-1])
        outputs7, outputs8, outputs9 = model(torch.flip(inputs, [-2]))
        predict_3 = torch.flip(outputs7, [-2])
        outputs10, outputs11, outputs12 = model(torch.flip(inputs, [-1, -2]))
        predict_4 = torch.flip(outputs10, [-1, -2])

        # 使用 outputs2 列表中的最后一个边界
        outputs_last = outputs2[-1]

        predict_list = outputs_last + predict_2 + predict_3 + predict_4

        pred = predict_list / 4.
        pred = torch.sigmoid(pred)
        outputs_last = pred.detach().cpu().numpy().squeeze()
        targets1 = targets1.detach().cpu().numpy().squeeze()

        res = np.zeros((256, 256))
        res[outputs_last > 0.5] = 255
        res[outputs_last <= 0.5] = 0
        res = morphology.remove_small_objects(res.astype(int), 1000)
        acc, precision, recall, F1, IoU = binary_accuracy(res, targets1)
我这样修改了代码，但是还是无法输出边界呢？

**Comment by long123524** [comment]
> > > 我改成output2了，会报错 0%| | 0/216 [00:00<?, ?it/s] Traceback (most recent call last): File "e:\DP\SEANet_torch\accuracy_evaluation.py", line 135, in predict_2 = torch.flip(outputs5, [-1]) TypeError: flip(): argument 'input' (position 1) must be Tensor, not list
> > 
> > 
> > output2内含多层级边界输出，所以是列表。你输出最后一个边界就好，outputs2[-1]
> 
> for i, (img_file_name, inputs, targets1, targets2, targets3) in enumerate( tqdm(valLoader) ): inputs = inputs.to(device) targets1 = targets1.to(device)
> 
> ```
>     outputs1, outputs2, outputs3 = model(inputs)
>     outputs4, outputs5, outputs6 = model(torch.flip(inputs, [-1]))
>     predict_2 = torch.flip(outputs4, [-1])
>     outputs7, outputs8, outputs9 = model(torch.flip(inputs, [-2]))
>     predict_3 = torch.flip(outputs7, [-2])
>     outputs10, outputs11, outputs12 = model(torch.flip(inputs, [-1, -2]))
>     predict_4 = torch.flip(outputs10, [-1, -2])
> 
>     # 使用 outputs2 列表中的最后一个边界
>     outputs_last = outputs2[-1]
> 
>     predict_list = outputs_last + predict_2 + predict_3 + predict_4
> 
>     pred = predict_list / 4.
>     pred = torch.sigmoid(pred)
>     outputs_last = pred.detach().cpu().numpy().squeeze()
>     targets1 = targets1.detach().cpu().numpy().squeeze()
> 
>     res = np.zeros((256, 256))
>     res[outputs_last > 0.5] = 255
>     res[outputs_last <= 0.5] = 0
>     res = morphology.remove_small_objects(res.astype(int), 1000)
>     acc, precision, recall, F1, IoU = binary_accuracy(res, targets1)
> ```
> 
> 我这样修改了代码，但是还是无法输出边界呢？

predict_2，predict_3， predict_4输出的并不是边界，而是mask。当输出边界时，需要对应修改相关代码。比如 predict_2 = torch.flip(outputs5[-1], [-1])。建议您加强代码理解与分析，这样会更方便你修改代码

**Comment by Muziyi687** [comment]
> > > > 我改成output2了，会报错 0%| | 0/216 [00:00<?, ?it/s] Traceback (most recent call last): File "e:\DP\SEANet_torch\accuracy_evaluation.py", line 135, in predict_2 = torch.flip(outputs5, [-1]) TypeError: flip(): argument 'input' (position 1) must be Tensor, not list
> > > 
> > > 
> > > output2内含多层级边界输出，所以是列表。你输出最后一个边界就好，outputs2[-1]
> > 
> > 
> > for i, (img_file_name, inputs, targets1, targets2, targets3) in enumerate( tqdm(valLoader) ): inputs = inputs.to(device) targets1 = targets1.to(device)
> > ```
> >     outputs1, outputs2, outputs3 = model(inputs)
> >     outputs4, outputs5, outputs6 = model(torch.flip(inputs, [-1]))
> >     predict_2 = torch.flip(outputs4, [-1])
> >     outputs7, outputs8, outputs9 = model(torch.flip(inputs, [-2]))
> >     predict_3 = torch.flip(outputs7, [-2])
> >     outputs10, outputs11, outputs12 = model(torch.flip(inputs, [-1, -2]))
> >     predict_4 = torch.flip(outputs10, [-1, -2])
> > 
> >     # 使用 outputs2 列表中的最后一个边界
> >     outputs_last = outputs2[-1]
> > 
> >     predict_list = outputs_last + predict_2 + predict_3 + predict_4
> > 
> >     pred = predict_list / 4.
> >     pred = torch.sigmoid(pred)
> >     outputs_last = pred.detach().cpu().numpy().squeeze()
> >     targets1 = targets1.detach().cpu().numpy().squeeze()
> > 
> >     res = np.zeros((256, 256))
> >     res[outputs_last > 0.5] = 255
> >     res[outputs_last <= 0.5] = 0
> >     res = morphology.remove_small_objects(res.astype(int), 1000)
> >     acc, precision, recall, F1, IoU = binary_accuracy(res, targets1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我这样修改了代码，但是还是无法输出边界呢？
> 
> predict_2，predict_3， predict_4输出的并不是边界，而是mask。当输出边界时，需要对应修改相关代码。比如 predict_2 = torch.flip(outputs5[-1], [-1])。建议您加强代码理解与分析，这样会更方便你修改代码

好的，谢谢您！
