### ISSUE TITLE
Issues with Output

### ISSUE THREAD

**Issue by kcsumesh** [long123524/SEANet_torch#12]
I tested the SEANet model (no changes made); however, the predicted extent mask has a different range. I believe it should be between 0 and 1.

![output_](https://github.com/user-attachments/assets/5bd7f1f6-0c9c-4841-ba8a-d5a4c83ad73d)

What threshold value have you used to generate binary output from the predicted extent mask?

**Comment by long123524** [comment]
> I tested the SEANet model (no changes made); however, the predicted extent mask has a different range. I believe it should be between 0 and 1.
> 
> ![output_](https://private-user-images.githubusercontent.com/101300358/363915432-5bd7f1f6-0c9c-4841-ba8a-d5a4c83ad73d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjQ4ODAsIm5iZiI6MTcyNTM2NDU4MCwicGF0aCI6Ii8xMDEzMDAzNTgvMzYzOTE1NDMyLTViZDdmMWY2LTBjOWMtNDg0MS1iYThhLWQ1YTRjODNhZDczZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMTU2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDZlZGJkMDg0YzhhZThjMmI1MTBlMmRjYjgxNGRjZDJjMWQwNmRhODk0Y2Q4MjA0MDNkY2ZkNDdlNWJmZGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nQ2REEPRPBRs7HGnj_gY6Mb2dy4j_tac0FrCI2Pnr5k)
> 
> What threshold value have you used to generate binary output from the predicted extent mask?

Do you use a Sigmoid function? After sigmoid, we adpot 0.5 as the threshold.

**Comment by kcsumesh** [comment]
Thanks for your reply.

![output1](https://github.com/user-attachments/assets/69f5bb60-0b64-4e38-806b-f594643ea279)
