### ISSUE TITLE
predict

### ISSUE THREAD

**Issue by smy123666** [long123524/SEANet_torch#13]
Hello, I did not have the label when I predicted, may I ask how to use this project to predict

**Comment by long123524** [comment]
> Hello, I did not have the label when I predicted, may I ask how to use this project to predict
When you have a trained weight, you not need the labels. But if you want to evaluate extraction accuracy, you will need them.

**Comment by smy123666** [comment]
> > Hello, I did not have the label when I predicted, may I ask how to use this project to predict
> > When you have a trained weight, you not need the labels. But if you want to evaluate extraction accuracy, you will need them.

Hello, I have trained a pth file, but when I ran it after modifying the path, I found that there was a program error running in parallel. However, I only used one gpu to run it. After the parallel running code was canceled, many errors with missing parameters would be reported again

**Comment by smy123666** [comment]
> > Hello, I did not have the label when I predicted, may I ask how to use this project to predict
> > When you have a trained weight, you not need the labels. But if you want to evaluate extraction accuracy, you will need them.

In addition, your readme file mentioned that the test data should be in the same format as the training data, but I only have image without labels. How can I predict the result and compare it with the original image

**Comment by smy123666** [comment]
> > Hello, I did not have the label when I predicted, may I ask how to use this project to predict
> > When you have a trained weight, you not need the labels. But if you want to evaluate extraction accuracy, you will need them.

Ok, in addition to that, I want to put in here a predicted image size of 1200*1200, the output is also 1200*1200, how do I do that

**Comment by long123524** [comment]
> > > Hello, I did not have the label when I predicted, may I ask how to use this project to predict
> > > When you have a trained weight, you not need the labels. But if you want to evaluate extraction accuracy, you will need them.
> 
> Ok, in addition to that, I want to put in here a predicted image size of 1200_1200, the output is also 1200_1200, how do I do that

consider using slide-window prediction methods

**Comment by long123524** [comment]
you can cancel the load function of label. Bo doing so, you not need the lables when you conduct predict.

**Comment by smy123666** [comment]
> you can cancel the load function of label. Bo doing so, you not need the lables when you conduct predict.

ok,thanks for your reply.
