### ISSUE TITLE
Pre trained weights

### ISSUE THREAD

**Issue by awadbahaa** [long123524/SEANet_torch#2]
Hello, 
I can not access the pretrained weights through the current link. 
can you provide an alternative link for international people, please.

**Comment by long123524** [comment]
You can access from https://drive.google.com/file/d/1idlA55pLM4EPxWQUvuL0kRj1SHfF32ct/view?usp=drive_link

**Comment by awadbahaa** [comment]
Thank you for replying so fast, but the link is restricted.
I cannot access the link, please allow access.

**Comment by long123524** [comment]
> Thank you for replying so fast, but the link is restricted. I cannot access the link, please allow access.

Sorry. Now you can access this link.

**Comment by awadbahaa** [comment]
Thank you very much.
