### ISSUE TITLE
Hi! Could you send the model to me? lmoyanc567@gmail.com Thanks!

### ISSUE THREAD

**Issue by Jessi533** [long123524/SEANet_torch#3]

**Comment by long123524** [comment]
The weight has already sent to your email.

**Comment by huazai-1994** [comment]
Could you please send the model to me? zjhxgg1994@gmail.com Thanks

**Comment by long123524** [comment]
> Could you please send the model to me? [zjhxgg1994@gmail.com](mailto:zjhxgg1994@gmail.com) Thanks

Thank your concern. Our model and the weight of vgg16 have released in the github, you can download and use it. You can also train our model on yourself dataset from scatch.

**Comment by 4ZZZ975** [comment]
> > Could you please send the model to me? [zjhxgg1994@gmail.com](mailto:zjhxgg1994@gmail.com) Thanks
> 
> Thank your concern. Our model and the weight of vgg16 have released in the github, you can download and use it. You can also train our model on yourself dataset from scatch.

hi，I can not find your model in the github ,Could you please send the model to me?Thanks.(I need PT file)

**Comment by 4ZZZ975** [comment]
> Could you please send the model to me? [zjhxgg1994@gmail.com](mailto:zjhxgg1994@gmail.com) Thanks

hi，I can not find your model in the github ,Could you please send the model to me?Thanks.(I need PT file)
email：zhiang333@163.com
