### ISSUE TITLE
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [2, 8, 3, 512, 512]

### ISSUE THREAD

**Issue by murdav** [long123524/SEANet_torch#4]
Dear authors,

I trivially copied the [file ](https://raw.githubusercontent.com/long123524/SEANet_torch/main/models.py) and instantiated the model as:

```
torch_device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', torch_device)
model = SEANet(num_classes=1)  # the same error with a different num_classes
print(summary(model, (8, 3, 512, 512)))  # the same error with a different batch_size
```

I got this error:

```
    343 def forward(self, x):
    344     # VGG
    345     img_H, img_W = x.shape[2], x.shape[3]
-> 347     conv1_1 = self.activ(self.conv1_1(x))

RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [2, 8, 3, 512, 512]
```

Could you help me?

Many thanks for your excellent work.

D

**Comment by long123524** [comment]
As you see, the input data is error size ([2, 8, 3, 512, 512]), however, it should be 4D data ([8, 3, 512, 512]). Thus, you need to check the data size, and ensure the data is true.

**Comment by long123524** [comment]
> Dear authors,
> 
> I trivially copied the [file ](https://raw.githubusercontent.com/long123524/SEANet_torch/main/models.py) and instantiated the model as:
> 
> ```
> torch_device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
> print('Using device:', torch_device)
> model = SEANet(num_classes=1)  # the same error with a different num_classes
> print(summary(model, (8, 3, 512, 512)))  # the same error with a different batch_size
> ```
> 
> I got this error:
> 
> ```
>     343 def forward(self, x):
>     344     # VGG
>     345     img_H, img_W = x.shape[2], x.shape[3]
> -> 347     conv1_1 = self.activ(self.conv1_1(x))
> 
> RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [2, 8, 3, 512, 512]
> ```
> 
> Could you help me?
> 
> Many thanks for your excellent work.
> 
> D

As you see, the input data is error size ([2, 8, 3, 512, 512]), however, it should be 4D data ([8, 3, 512, 512]). Thus, you need to check the data size, and ensure the data is true.

**Comment by murdav** [comment]
I instantiated the model as in https://github.com/long123524/SEANet_torch/blob/main/train.py#L91 to print the network architecture using the `summary` function (`from torchsummary import summary`). Well, a simpler `print(model)` works. 
However, I still don't understand why the other function does not work.
