### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by chl916185** [long123524/SEANet_torch#5]
论文中的数据集可以分享下吗，仅用于研究使用
@long123524

**Comment by long123524** [comment]
> 论文中的数据集可以分享下吗，仅用于研究使用 @long123524

一景高分影像可利用在https://github.com/long123524/BsiNet-torch，对于中等分辨率影像，欧洲也有公开的地块数据集可利用https://www.pdok.nl/。我们也正在准备公开一些可用的高分辨率的地块数据集，请关注我们的后续研究，谢谢！

**Comment by chl916185** [comment]
> > 论文中的数据集可以分享下吗，仅用于研究使用 @long123524
> 
> 一景高分影像可利用在[https://github.com/long123524/BsiNet-torch，对于中等分辨率影像，欧洲也有公开的地块数据集可利用https://www.pdok.nl/。我们也正在准备公开一些可用的高分辨率的地块数据集，请关注我们的后续研究，谢谢！](https://github.com/long123524/BsiNet-torch%EF%BC%8C%E5%AF%B9%E4%BA%8E%E4%B8%AD%E7%AD%89%E5%88%86%E8%BE%A8%E7%8E%87%E5%BD%B1%E5%83%8F%EF%BC%8C%E6%AC%A7%E6%B4%B2%E4%B9%9F%E6%9C%89%E5%85%AC%E5%BC%80%E7%9A%84%E5%9C%B0%E5%9D%97%E6%95%B0%E6%8D%AE%E9%9B%86%E5%8F%AF%E5%88%A9%E7%94%A8https://www.pdok.nl/%E3%80%82%E6%88%91%E4%BB%AC%E4%B9%9F%E6%AD%A3%E5%9C%A8%E5%87%86%E5%A4%87%E5%85%AC%E5%BC%80%E4%B8%80%E4%BA%9B%E5%8F%AF%E7%94%A8%E7%9A%84%E9%AB%98%E5%88%86%E8%BE%A8%E7%8E%87%E7%9A%84%E5%9C%B0%E5%9D%97%E6%95%B0%E6%8D%AE%E9%9B%86%EF%BC%8C%E8%AF%B7%E5%85%B3%E6%B3%A8%E6%88%91%E4%BB%AC%E7%9A%84%E5%90%8E%E7%BB%AD%E7%A0%94%E7%A9%B6%EF%BC%8C%E8%B0%A2%E8%B0%A2%EF%BC%81)
好的，后续公开的地块数据集，大概什么时间会公布呢

**Comment by chl916185** [comment]
> > 论文中的数据集可以分享下吗，仅用于研究使用 @long123524
> 
> 一景高分影像可利用在[https://github.com/long123524/BsiNet-torch，对于中等分辨率影像，欧洲也有公开的地块数据集可利用https://www.pdok.nl/。我们也正在准备公开一些可用的高分辨率的地块数据集，请关注我们的后续研究，谢谢！](https://github.com/long123524/BsiNet-torch%EF%BC%8C%E5%AF%B9%E4%BA%8E%E4%B8%AD%E7%AD%89%E5%88%86%E8%BE%A8%E7%8E%87%E5%BD%B1%E5%83%8F%EF%BC%8C%E6%AC%A7%E6%B4%B2%E4%B9%9F%E6%9C%89%E5%85%AC%E5%BC%80%E7%9A%84%E5%9C%B0%E5%9D%97%E6%95%B0%E6%8D%AE%E9%9B%86%E5%8F%AF%E5%88%A9%E7%94%A8https://www.pdok.nl/%E3%80%82%E6%88%91%E4%BB%AC%E4%B9%9F%E6%AD%A3%E5%9C%A8%E5%87%86%E5%A4%87%E5%85%AC%E5%BC%80%E4%B8%80%E4%BA%9B%E5%8F%AF%E7%94%A8%E7%9A%84%E9%AB%98%E5%88%86%E8%BE%A8%E7%8E%87%E7%9A%84%E5%9C%B0%E5%9D%97%E6%95%B0%E6%8D%AE%E9%9B%86%EF%BC%8C%E8%AF%B7%E5%85%B3%E6%B3%A8%E6%88%91%E4%BB%AC%E7%9A%84%E5%90%8E%E7%BB%AD%E7%A0%94%E7%A9%B6%EF%BC%8C%E8%B0%A2%E8%B0%A2%EF%BC%81)
