### ISSUE TITLE
图片无法识别

### ISSUE THREAD

**Issue by whj510** [long123524/SEANet_torch#6]
你好，我在训练的时候总是出现图片无法识别的问题，请问这是什么原因呀，我用的是GF2的4波段tif数据。

![Snipaste_2024-04-15_17-09-24](https://github.com/long123524/SEANet_torch/assets/101308556/d0560918-576a-429d-b026-49f8f3add139)

**Comment by long123524** [comment]
> 你好，我在训练的时候总是出现图片无法识别的问题，请问这是什么原因呀，我用的是GF2的4波段tif数据。
> 
> ![Snipaste_2024-04-15_17-09-24](https://private-user-images.githubusercontent.com/101308556/322421815-d0560918-576a-429d-b026-49f8f3add139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODU0MDAsIm5iZiI6MTcxMzE4NTEwMCwicGF0aCI6Ii8xMDEzMDg1NTYvMzIyNDIxODE1LWQwNTYwOTE4LTU3NmEtNDI5ZC1iMDI2LTQ5ZjhmM2FkZDEzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxMjQ1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTY3NDA3MTYxZWE4M2EwYTA3MmJkYmZmMzhkMmQzNmEyODZiMTNkNGEwNTRiNTMyMDc4MjNlMDIwMWFjYTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gRVk0voTChaJNwhWqeA0StoJRWWJfSbeI7_wSf1Rixs)

1.检查路径是否正常；2.检查图片是否能被常用软件正常打开（例如Arcgis）；3.检查图片波段或位数。谢谢！

**Comment by whj510** [comment]
> > 你好，我在训练的时候总是出现图片无法识别的问题，请问这是什么原因呀，我用的是GF2的4波段tif数据。
> > ![Snipaste_2024-04-15_17-09-24](https://private-user-images.githubusercontent.com/101308556/322421815-d0560918-576a-429d-b026-49f8f3add139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODU0MDAsIm5iZiI6MTcxMzE4NTEwMCwicGF0aCI6Ii8xMDEzMDg1NTYvMzIyNDIxODE1LWQwNTYwOTE4LTU3NmEtNDI5ZC1iMDI2LTQ5ZjhmM2FkZDEzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxMjQ1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTY3NDA3MTYxZWE4M2EwYTA3MmJkYmZmMzhkMmQzNmEyODZiMTNkNGEwNTRiNTMyMDc4MjNlMDIwMWFjYTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gRVk0voTChaJNwhWqeA0StoJRWWJfSbeI7_wSf1Rixs)
> 
> 1.检查路径是否正常；2.检查图片是否能被常用软件正常打开（例如Arcgis）；3.检查图片波段或位数。谢谢！

好的谢谢大佬耐心回复
