### ISSUE TITLE
有训练好的模型么，求求了，大哭

### ISSUE THREAD

**Issue by qk1997** [long123524/SEANet_torch#7]

**Comment by long123524** [comment]
> _No description provided.

你可以利用我们提供的数据集进行训练，仅需要改动路径，详见train.py。在模型BsiNet中，我们提供了权重可用于直接测试https://github.com/long123524/BsiNet-torch。

**Comment by qk1997** [comment]
您好，我想问下您的设备以及大概训练了多久？

**Comment by long123524** [comment]
> 您好，我想问下您的设备以及大概训练了多久？

见论文实验细节和附录文件

**Comment by 4ZZZ975** [comment]
> 您好，我想问下您的设备以及大概训练了多久？

你好，我想问一下你有训练好的模型吗 @qk1997 谢谢
