### ISSUE TITLE
不用dist_contour和contour

### ISSUE THREAD

**Issue by Muziyi687** [long123524/SEANet_torch#8]
如果我不用dist_contour和contour会有影响吗？因为我换了数据，生成dist_contour是有问题的，我在arcgispro上打开是灰色的整张图片，所以想去掉dist_contour和contour来试验

**Comment by long123524** [comment]
> 如果我不用dist_contour和contour会有影响吗？因为我换了数据，生成dist_contour是有问题的，我在arcgispro上打开是灰色的整张图片，所以想去掉dist_contour和contour来试验

有影响。去掉之后就是单任务模型了

**Comment by Muziyi687** [comment]
谢谢您，还有个问题，就是转成contour和dist_contour的二值化图像，栅格图像中的255值是不是必须是面，我发现我的二值化数据是线要素转化成栅格来的，是不是在生成contour和dist_contour的过程会出现问题？

**Comment by long123524** [comment]
> 谢谢您，还有个问题，就是转成contour和dist_contour的二值化图像，栅格图像中的255值是不是必须是面，我发现我的二值化数据是线要素转化成栅格来的，是不是在生成contour和dist_contour的过程会出现问题？

是的，是面要素转过来的栅格mask
