### ISSUE TITLE
结果拼接

### ISSUE THREAD

**Issue by Muziyi687** [long123524/SEANet_torch#9]
请问一下，您有没有可以将预测结果又拼回一整张图片的代码，也就是cai_duobands.py的逆过程，谢谢！

**Comment by long123524** [comment]
> 请问一下，您有没有可以将预测结果又拼回一整张图片的代码，也就是cai_duobands.py的逆过程，谢谢！

你可以使用envi软件或者按照地理坐标顺序拼接即可

**Comment by Muziyi687** [comment]
> > 请问一下，您有没有可以将预测结果又拼回一整张图片的代码，也就是cai_duobands.py的逆过程，谢谢！
> 
> 你可以使用envi软件或者按照地理坐标顺序拼接即可

好的，谢谢您！
